FROM qmcgaw/latexdevcontainer:latest
# install fullpage.sty and marvosym.sty
USER root
RUN apt update && apt-get install texlive-latex-extra --no-install-recommends -y && apt-get install texlive-fonts-recommended -y
